export default {
  '-- action': { type: 'separator', title: 'Action' },
  button: 'Button',
  'button-group': 'Button Group',
  toggle: 'Toggle',
  'toggle-group': 'Toggle Group',
  '-- form': { type: 'separator', title: 'Form' },
  field: 'Field',
  input: 'Input',
  'input-group': 'Input Group',
  'input-otp': 'Input OTP',
  textarea: 'Textarea',
  checkbox: 'Checkbox',
  'radio-group': 'Radio Group',
  switch: 'Switch',
  slider: 'Slider',
  select: 'Select',
  combobox: 'Combobox',
  'date-picker': 'Date Picker',
  '-- feedback': { type: 'separator', title: 'Feedback' },
  'tooltip': 'Tooltip',
  'hover-card': 'Hover Card',
  'popover': 'Popover',
  'alert': 'Alert',
  'badge': 'Badge',
  'kbd': 'Kbd',
  'progress': 'Progress',
  'skeleton': 'Skeleton',
  'spinner': 'Spinner',
  'sonner': 'Sonner',
  'alert-dialog': 'Alert Dialog',
  '-- layout': { type: 'separator', title: 'Layout' },
  accordion: 'Accordion',
  card: 'Card',
  collapsible: 'Collapsible',
  command: 'Command',
  dialog: 'Dialog',
  drawer: 'Drawer',
  empty: 'Empty',
  separator: 'Separator',
  sheet: 'Sheet',
  '-- text': { type: 'separator', title: 'Text' },
  display: 'Display',
  title: 'Title',
  body: 'Body',
  code: 'Code',
  label: 'Label',
  '-- content': { type: 'separator', title: 'Content' },
  avatar: 'Avatar',
  calendar: 'Calendar',
  carousel: 'Carousel',
  'context-menu': 'Context Menu',
  '-- navigation': { type: 'separator', title: 'Navigation' },
  breadcrumb: 'Breadcrumb',
  'dropdown-menu': 'Dropdown Menu',
  menubar: 'Menubar',
  'navigation-menu': 'Navigation Menu',
  pagination: 'Pagination',
  tabs: 'Tabs',
  '-- data': { type: 'separator', title: 'Data' },
  'data-table': 'Data Table',
  'item': 'Item',
  'table': 'Table',
  '-- chart': { type: 'separator', title: 'Chart' },
  'chart-bar': 'Bar',
  'chart-line': 'Line',
  'chart-area': 'Area',
  'chart-pie': 'Pie',
  'chart-radar': 'Radar',
  'chart-radial': 'Radial',
}
