export default {
  '-- action': { type: 'separator', title: 'Action' },
  button: 'Button',
  'button-group': 'Button Group',
  '-- form': { type: 'separator', title: 'Form' },
  input: 'Input',
  checkbox: 'Checkbox',
  combobox: 'Combobox',
  'date-picker': 'Date Picker',
  field: 'Field',
  'input-group': 'Input Group',
  'input-otp': 'Input OTP',
  '-- layout': { type: 'separator', title: 'Layout' },
  accordion: 'Accordion',
  card: 'Card',
  collapsible: 'Collapsible',
  command: 'Command',
  dialog: 'Dialog',
  drawer: 'Drawer',
  empty: 'Empty',
  separator: 'Separator',
  '-- text': { type: 'separator', title: 'Text' },
  label: 'Label',
  '-- content': { type: 'separator', title: 'Content' },
  'aspect-ratio': 'Aspect Ratio',
  avatar: 'Avatar',
  calendar: 'Calendar',
  carousel: 'Carousel',
  'context-menu': 'Context Menu',
  '-- feedback': { type: 'separator', title: 'Feedback' },
  alert: 'Alert',
  'alert-dialog': 'Alert Dialog',
  badge: 'Badge',
  'hover-card': 'Hover Card',
  '-- navigation': { type: 'separator', title: 'Navigation' },
  breadcrumb: 'Breadcrumb',
  'dropdown-menu': 'Dropdown Menu',
  '-- data': { type: 'separator', title: 'Data' },
  'data-table': 'Data Table',
  item: 'Item',
  '-- chart': { type: 'separator', title: 'Chart' },
  'chart-bar': 'Bar',
  'chart-line': 'Line',
  'chart-area': 'Area',
  'chart-pie': 'Pie',
  'chart-radar': 'Radar',
  'chart-radial': 'Radial',
}
